version: "3.8"

services:
  foxCMS-redis:
    image: redis:alpine
    restart: always
    command: redis-server --requirepass password
    networks:
      - fox-cms
    ports:
      - "0.0.0.0:6381:6379"

  foxCMS-user-service-db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 0.0.0.0:5436:5432
    networks:
      - fox-cms

  foxCMS-blog-service-db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 0.0.0.0:5437:5432
networks:
  fox-cms:
